version: "3"
services:
  tests:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    container_name: bot-woodhouse
    command: bash -c "npm install && npm start"